SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

PROJECT_NAME := resign-agent-commits
SOURCE_DIR := src
LIST_SOURCE := $(SOURCE_DIR)/list_repos.bash
RESIGN_SOURCE := $(SOURCE_DIR)/resign_commits.bash
SOURCE_SCRIPTS := $(LIST_SOURCE) $(RESIGN_SOURCE)

DIST_DIR := dist
LIST_DEV := $(DIST_DIR)/list_repos.dev.bash
LIST_SCRIPT := $(DIST_DIR)/list_repos.bash
LIST_MIN := $(DIST_DIR)/list_repos.min.bash
RESIGN_DEV := $(DIST_DIR)/resign_commits.dev.bash
RESIGN_SCRIPT := $(DIST_DIR)/resign_commits.bash
RESIGN_MIN := $(DIST_DIR)/resign_commits.min.bash
DIST_SCRIPTS := $(LIST_DEV) $(LIST_SCRIPT) $(LIST_MIN) $(RESIGN_DEV) $(RESIGN_SCRIPT) $(RESIGN_MIN)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_SCRIPTS))
LEGACY_CHECKSUMS := $(addsuffix .256,$(DIST_SCRIPTS))

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.4.1
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := 5131ebb6a3a85e1d76624a37146c2442b2e57be6ffd8139b9590d28239876701
BASH_MINIFIER := $(VENDOR_DIR)/bash-minifier.bash
DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
ADRCTL := $(VENDOR_DIR)/adrctl.bash
BASHLOG := $(VENDOR_DIR)/bashlog.dev.bash

ADR_DIR := doc/adr
ADR_INDEX_INTRO := $(ADR_DIR)/README.intro.md
ADR_INDEX_OUTRO := $(ADR_DIR)/README.outro.md
ADR_INDEX_FILE := $(ADR_DIR)/README.md
REFERENCE_DOC_DIR := doc/reference
TEST_RESULTS_DIR := test-results

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell commit="$$(git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')"; if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && [[ -n "$$(git status --porcelain --untracked-files=normal -- Makefile dependencies.txt src tests doc .github 2>/dev/null)" ]]; then printf '%s-dirty' "$$commit"; else printf '%s' "$$commit"; fi)
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')
SHFMT_ARGUMENTS := -i 2 -bn -ci -sr -kp

.PHONY: all adr-index build check checksums clean deps deps-check distclean docs docs-clean FORCE format test test-report verify-bashdeps

all: deps
	$(MAKE) --no-print-directory build

build: $(DIST_SCRIPTS) $(DIST_CHECKSUMS)
	rm -f $(LEGACY_CHECKSUMS)

define BUILD_DEV
	@mkdir -p "$(DIST_DIR)"
	@tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; { \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Project: $(PROJECT_NAME)'; \
		printf '%s\n' '# Artifact: $(notdir $@)'; \
		printf '%s\n' '# Version: $(VERSION)'; \
		printf '%s\n' '# Build date: $(BUILD_DATE)'; \
		printf '%s\n' '# Build commit: $(BUILD_COMMIT)'; \
		printf '%s\n' '# Maintained source: $<'; \
		printf '\n'; \
		printf 'RESIGN_AGENT_COMMITS_VERSION=%q\n' "$(VERSION)"; \
		printf 'RESIGN_AGENT_COMMITS_BUILD_DATE=%q\n' "$(BUILD_DATE)"; \
		printf 'RESIGN_AGENT_COMMITS_BUILD_COMMIT=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		{ IFS= read -r _; while IFS= read -r line || [[ -n "$$line" ]]; do printf '%s\n' "$$line"; done; } <"$<"; \
	} >"$$tmp"; chmod 0755 "$$tmp"; bash -n "$$tmp"; mv "$$tmp" "$@"; trap - EXIT
endef

$(LIST_DEV): $(LIST_SOURCE)
	$(BUILD_DEV)

$(RESIGN_DEV): $(RESIGN_SOURCE)
	$(BUILD_DEV)

$(LIST_SCRIPT): $(LIST_DEV)
	@tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; first=true; while IFS= read -r line || [[ -n "$$line" ]]; do if $$first; then printf '%s\n' "$$line"; first=false; continue; fi; [[ "$$line" =~ ^[[:space:]]*# ]] && continue; printf '%s\n' "$$line"; done <"$<" >"$$tmp"; chmod 0755 "$$tmp"; bash -n "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

$(RESIGN_SCRIPT): $(RESIGN_DEV)
	@tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; first=true; while IFS= read -r line || [[ -n "$$line" ]]; do if $$first; then printf '%s\n' "$$line"; first=false; continue; fi; [[ "$$line" =~ ^[[:space:]]*# ]] && continue; printf '%s\n' "$$line"; done <"$<" >"$$tmp"; chmod 0755 "$$tmp"; bash -n "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

$(LIST_MIN): $(LIST_SCRIPT) $(BASH_MINIFIER)
	@test -f "$(BASH_MINIFIER)" || { printf '%s\n' 'Missing build dependency vendor/bash-minifier.bash; run make deps or make all' >&2; exit 1; }
	@tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; bash "$(BASH_MINIFIER)" -F <"$<" >"$$tmp"; chmod 0755 "$$tmp"; bash -n "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

$(RESIGN_MIN): $(RESIGN_SCRIPT) $(BASH_MINIFIER)
	@test -f "$(BASH_MINIFIER)" || { printf '%s\n' 'Missing build dependency vendor/bash-minifier.bash; run make deps or make all' >&2; exit 1; }
	@tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; bash "$(BASH_MINIFIER)" -F <"$<" >"$$tmp"; chmod 0755 "$$tmp"; bash -n "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

$(DIST_DIR)/%.bash.sha256: $(DIST_DIR)/%.bash
	@digest=''; if command -v sha256sum >/dev/null 2>&1; then read -r digest _ < <(sha256sum "$<"); elif command -v shasum >/dev/null 2>&1; then read -r digest _ < <(shasum -a 256 "$<"); else printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; exit 1; fi; printf '%s  %s\n' "$$digest" "$(notdir $<)" >"$@.tmp"; mv "$@.tmp" "$@"

checksums: build

check:
	@for source in $(SOURCE_SCRIPTS); do bash -n "$$source"; done
	shellcheck $(SOURCE_SCRIPTS) tests/*.bash tests/*.bats

format:
	shfmt $(SHFMT_ARGUMENTS) -w $(SOURCE_SCRIPTS) tests/*.bash tests/*.bats

FORCE:

$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { path=$$1; if command -v sha256sum >/dev/null 2>&1; then printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; elif command -v shasum >/dev/null 2>&1; then [[ "$$(shasum -a 256 "$$path" | awk '{print $$1}')" == "$(BASHDEPS_SHA256)" ]]; else return 2; fi; }; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; fi; \
	if [[ -f "$@" ]] && verify_hash "$@"; then chmod 0755 "$@"; exit 0; fi; \
	tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; \
	if command -v curl >/dev/null 2>&1; then curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; elif command -v wget >/dev/null 2>&1; then wget -qO "$$tmp" "$(BASHDEPS_URL)"; else printf '%s\n' 'curl or wget is required to bootstrap bashdeps.bash' >&2; exit 1; fi; \
	verify_hash "$$tmp" || { printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; exit 1; }; chmod 0755 "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable bashdeps bootstrap; run make deps' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps' >&2; exit 1; }; elif command -v shasum >/dev/null 2>&1; then [[ "$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')" == "$(BASHDEPS_SHA256)" ]] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps' >&2; exit 1; }; else printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; fi

deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

adr-index:
	@test -f "$(ADRCTL)" && test ! -L "$(ADRCTL)" || { printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps or make all' >&2; exit 1; }
	@test -f "$(ADR_INDEX_INTRO)" || { printf 'Missing ADR index introduction: %s\n' "$(ADR_INDEX_INTRO)" >&2; exit 1; }
	@test -f "$(ADR_INDEX_OUTRO)" || { printf 'Missing ADR index conclusion: %s\n' "$(ADR_INDEX_OUTRO)" >&2; exit 1; }
	@tmp="$$(mktemp "$(ADR_INDEX_FILE).tmp.XXXXXX")"; trap 'rm -f "$$tmp"' EXIT; bash "$(ADRCTL)" generate toc -i "$(ADR_INDEX_INTRO)" -o "$(ADR_INDEX_OUTRO)" >"$$tmp"; mv "$$tmp" "$(ADR_INDEX_FILE)"; trap - EXIT

docs:
	@test -f "$(DOXYGEN_BASH_FILTER)" || { printf '%s\n' 'Missing documentation dependency vendor/doxygen-bash.awk; run make deps or make all' >&2; exit 1; }
	@test -f "$(ADRCTL)" && test ! -L "$(ADRCTL)" || { printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps or make all' >&2; exit 1; }
	$(MAKE) --no-print-directory docs-clean
	$(MAKE) --no-print-directory adr-index
	chmod 0755 "$(DOXYGEN_BASH_FILTER)"
	RESIGN_AGENT_COMMITS_DOXYGEN_PROJECT_NAME="$(PROJECT_NAME)" doxygen Doxyfile

docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"
	rm -f "$(ADR_INDEX_FILE)" "$(ADR_INDEX_FILE).tmp" "$(ADR_INDEX_FILE).tmp."*

test: build
	@set -e; for artifact in $(DIST_SCRIPTS); do printf 'Testing %s\n' "$$artifact"; RAC_ARTIFACT="$(CURDIR)/$$artifact" bats tests; done

test-report: build
	@rm -rf "$(TEST_RESULTS_DIR)"; mkdir -p "$(TEST_RESULTS_DIR)"; set -e; for artifact in $(DIST_SCRIPTS); do label="$$(basename "$$artifact" .bash)"; printf 'Testing %s\n' "$$artifact"; RAC_ARTIFACT="$(CURDIR)/$$artifact" bats --formatter junit tests >"$(TEST_RESULTS_DIR)/bats-$$label.xml"; done

clean: docs-clean
	rm -rf "$(DIST_DIR)" "$(TEST_RESULTS_DIR)"

distclean: clean
	rm -rf "$(VENDOR_DIR)"
