# Canonical development, validation, documentation, and release entry points.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

PROJECT_NAME ?= template-bash
ifneq ($(words $(PROJECT_NAME)),1)
$(error PROJECT_NAME must be one non-empty whitespace-free word)
endif
DIST_DIR := dist
DIST_DEV_SCRIPT := $(DIST_DIR)/$(PROJECT_NAME).dev.bash
DIST_SCRIPT := $(DIST_DIR)/$(PROJECT_NAME).bash
DIST_MIN_SCRIPT := $(DIST_DIR)/$(PROJECT_NAME).min.bash
DIST_SCRIPTS := $(DIST_DEV_SCRIPT) $(DIST_SCRIPT) $(DIST_MIN_SCRIPT)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_SCRIPTS))
LEGACY_CHECKSUMS := $(addsuffix .256,$(DIST_SCRIPTS))
CORE_SOURCE_FILES := lib/plugin-registry.bash
PLUGIN_SOURCE_FILES := $(sort $(wildcard lib/plugins/*.bash))
ENTRYPOINT_SOURCE := src/main.bash
SOURCE_FILES := $(CORE_SOURCE_FILES) $(PLUGIN_SOURCE_FILES) $(ENTRYPOINT_SOURCE)
TEST_SCRIPTS := $(sort $(wildcard tests/*.bats))
TEST_RESULTS_DIR := test-results

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.6
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := bb6c807fa12c010950bda06172ac0611d278c57aca1f8352f41502d0d76b4e6c
BASH_MINIFIER := $(VENDOR_DIR)/bash-minifier.bash
DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
ADRCTL := $(VENDOR_DIR)/adrctl.bash
ADR_DIR := doc/adr
ADR_INDEX_INTRO := $(ADR_DIR)/README.intro.md
ADR_INDEX_OUTRO := $(ADR_DIR)/README.outro.md
ADR_INDEX_FILE := $(ADR_DIR)/README.md
REFERENCE_DOC_DIR := doc/reference

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell commit="$$(git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')"; if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && [[ -n "$$(git status --porcelain --untracked-files=normal -- Makefile dependencies.txt src lib 2>/dev/null)" ]]; then printf '%s-dirty' "$$commit"; else printf '%s' "$$commit"; fi)
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')
SHFMT_ARGUMENTS := -i 2 -bn -ci -sr -kp

.PHONY: all adr-index build check checksums clean deps deps-check distclean docs docs-clean FORCE format test test-report verify-bashdeps

## Synchronize repository dependencies, then build consumer artifacts.
all: deps
	$(MAKE) --no-print-directory build

## Build all standalone artifacts and their checksum companions without network access.
build: $(DIST_SCRIPTS) $(DIST_CHECKSUMS)
	rm -f $(LEGACY_CHECKSUMS)

## Assemble the fully documented development artifact in deterministic source order.
## FORCE is intentional because VERSION and provenance are build inputs that Make
## cannot infer from source mtimes.  Repeated builds remain byte-stable when those
## inputs are unchanged, while an explicit VERSION override is never silently
## ignored because an older artifact already exists.
$(DIST_DEV_SCRIPT): FORCE $(SOURCE_FILES)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Project: $(PROJECT_NAME)'; \
		printf '%s\n' '# Version: $(VERSION)'; \
		printf '%s\n' '# Build date: $(BUILD_DATE)'; \
		printf '%s\n' '# Build commit: $(BUILD_COMMIT)'; \
		printf '%s\n' '# Core source: $(CORE_SOURCE_FILES)'; \
		printf '%s\n' '# Discovered plugins: $(PLUGIN_SOURCE_FILES)'; \
		printf '%s\n' '# Entrypoint: $(ENTRYPOINT_SOURCE)'; \
		printf '\n'; \
		printf 'BASH_STARTER_PROJECT_NAME=%q\n' "$(PROJECT_NAME)"; \
		printf 'BASH_STARTER_VERSION=%q\n' "$(VERSION)"; \
		printf 'BASH_STARTER_BUILD_DATE=%q\n' "$(BUILD_DATE)"; \
		printf 'BASH_STARTER_BUILD_COMMIT=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		cat $(SOURCE_FILES); \
	} >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

## Remove full-line comments from the assembled development artifact, preserving its shebang.
$(DIST_SCRIPT): $(DIST_DEV_SCRIPT)
	sed '1b; /^[[:space:]]*#/d' "$<" >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

## Minify the ordinary artifact using already-prepared Bash-Minifier state.
$(DIST_MIN_SCRIPT): $(DIST_SCRIPT)
	@test -f "$(BASH_MINIFIER)" || { printf '%s\n' 'Missing build dependency vendor/bash-minifier.bash; run make deps or make all' >&2; exit 1; }
	bash "$(BASH_MINIFIER)" -F <"$(DIST_SCRIPT)" >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

## Generate one portable SHA-256 checksum companion for an executable artifact.
$(DIST_DIR)/%.bash.sha256: $(DIST_DIR)/%.bash
	@digest=''; \
	if command -v sha256sum >/dev/null 2>&1; then digest="$$(sha256sum "$<" | awk '{print $$1}')"; \
	elif command -v shasum >/dev/null 2>&1; then digest="$$(shasum -a 256 "$<" | awk '{print $$1}')"; \
	else printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; exit 1; fi; \
	printf '%s  %s\n' "$$digest" "$(notdir $<)" >"$@.tmp"; mv "$@.tmp" "$@"

checksums: build

## Validate maintained Bash syntax and run ShellCheck against maintained source.
check:
	@for source in $(SOURCE_FILES); do bash -n "$$source"; done
	shellcheck $(SOURCE_FILES)

## Format maintained Bash using the same arguments configured for MegaLinter.
format:
	shfmt $(SHFMT_ARGUMENTS) -w $(SOURCE_FILES)

## Run the behavior suite against every generated artifact flavor.
test: build
	@set -e; for artifact in $(DIST_SCRIPTS); do printf 'Testing %s\n' "$$artifact"; BASH_STARTER_ARTIFACT="$${PWD}/$$artifact" bats $(TEST_SCRIPTS); done

## Run every artifact flavor and emit one JUnit report per flavor.
test-report: build
	@mkdir -p "$(TEST_RESULTS_DIR)"
	@set -e; for entry in 'development|$(DIST_DEV_SCRIPT)' 'stripped|$(DIST_SCRIPT)' 'minified|$(DIST_MIN_SCRIPT)'; do label="$${entry%%|*}"; artifact="$${entry#*|}"; BASH_STARTER_ARTIFACT="$${PWD}/$$artifact" bats --formatter junit $(TEST_SCRIPTS) >"$(TEST_RESULTS_DIR)/bats-$${label}.xml"; done

FORCE:

## Bootstrap only bashdeps directly, verifying pinned bytes before execution.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { path=$$1; if command -v sha256sum >/dev/null 2>&1; then printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; elif command -v shasum >/dev/null 2>&1; then [[ "$$(shasum -a 256 "$$path" | awk '{print $$1}')" == "$(BASHDEPS_SHA256)" ]]; else return 2; fi; }; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; fi; \
	if [[ -f "$@" ]] && verify_hash "$@"; then chmod 0755 "$@"; exit 0; fi; \
	tmp="$@.tmp"; trap 'rm -f "$$tmp"' EXIT; \
	if command -v curl >/dev/null 2>&1; then curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	elif command -v wget >/dev/null 2>&1; then wget -qO "$$tmp" "$(BASHDEPS_URL)"; \
	else printf '%s\n' 'curl or wget is required to bootstrap bashdeps.bash' >&2; exit 1; fi; \
	if ! verify_hash "$$tmp"; then printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; exit 1; fi; \
	chmod 0755 "$$tmp"; mv "$$tmp" "$@"; trap - EXIT

## Verify the pinned bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable bashdeps bootstrap; run make deps' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps' >&2; exit 1; }; elif command -v shasum >/dev/null 2>&1; then [[ "$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')" == "$(BASHDEPS_SHA256)" ]] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps' >&2; exit 1; }; else printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; fi

## Synchronize manifest-managed scripts, libraries, filters, and assets; may use network.
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

## Verify prepared dependency state without network access or repair.
deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

## Generate the linked ADR landing page from maintained framing and ADR source.
adr-index:
	@test -f "$(ADRCTL)" && test ! -L "$(ADRCTL)" || { \
		printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps or make all' >&2; \
		exit 1; \
	}
	@test -f "$(ADR_INDEX_INTRO)" || { printf 'Missing ADR index introduction: %s\n' "$(ADR_INDEX_INTRO)" >&2; exit 1; }
	@test -f "$(ADR_INDEX_OUTRO)" || { printf 'Missing ADR index conclusion: %s\n' "$(ADR_INDEX_OUTRO)" >&2; exit 1; }
	@tmp="$$(mktemp "$(ADR_INDEX_FILE).tmp.XXXXXX")"; \
	trap 'rm -f "$$tmp"' EXIT; \
	bash "$(ADRCTL)" generate toc -i "$(ADR_INDEX_INTRO)" -o "$(ADR_INDEX_OUTRO)" >"$$tmp"; \
	mv "$$tmp" "$(ADR_INDEX_FILE)"; \
	trap - EXIT

## Generate Doxygen reference documentation from already-prepared dependency state.
docs:
	@test -f "$(DOXYGEN_BASH_FILTER)" || { printf '%s\n' 'Missing documentation dependency vendor/doxygen-bash.awk; run make deps or make all' >&2; exit 1; }
	@test -f "$(ADRCTL)" && test ! -L "$(ADRCTL)" || { printf '%s\n' 'Missing documentation dependency vendor/adrctl.bash; run make deps or make all' >&2; exit 1; }
	$(MAKE) --no-print-directory docs-clean
	$(MAKE) --no-print-directory adr-index
	chmod 0755 "$(DOXYGEN_BASH_FILTER)"
	BASH_STARTER_DOXYGEN_PROJECT_NAME="$(PROJECT_NAME)" doxygen Doxyfile

## Remove generated reference documentation and generated ADR navigation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"
	rm -f "$(ADR_INDEX_FILE)" "$(ADR_INDEX_FILE).tmp" "$(ADR_INDEX_FILE).tmp."*

## Remove generated build and test-report artifacts while retaining dependency state.
clean: docs-clean
	rm -rf "$(DIST_DIR)" "$(TEST_RESULTS_DIR)"

## Remove all generated state, including repository dependencies.
distclean: clean
	rm -rf "$(VENDOR_DIR)"
